### ISSUE TITLE
perl::module: No matching entry for selector parameter with value ''

### ISSUE THREAD

**Issue by msweetser** [example42/puppet-perl#24]
When using the following resource:

`perl::module { 'Time::Piece': }`

I receive the following error:

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: No matching entry for selector parameter with value '' at /etc/puppetlabs/code/environments/development/modules/perl/manifests/module.pp:32:15 `

The code there has to do with package_downcase, defined in params.pp:

```
  $pkg_name = $package_downcase ? {
    true  => downcase(regsubst($name,'::','-')),
    false => regsubst($name,'::','-'),
  }
```

I did some debugging output and found that $package_downcase is empty, which breaks the selector.  Adding a default clause to the selector kludges around this but doesn't fix the underlying issue.

Adding an "include perl" statement before the module definition in my manifest alleviates the problem, but this doesn't seem to be mentioned in the documentation.

**Comment by alvagante** [comment]
Actually the solution should be, as you noted, to add an include perl before using the perl::module define. Going to update the docs coherently.
