### ISSUE TITLE
RedHat/Centos 7 - perl-doc package fails

### ISSUE THREAD

**Issue by kariboe** [example42/puppet-perl#27]
## Expected Behavior 

include ::perl 

OR 

class {'::perl':
        doc_package => '',
}

Expect to have perl and cpan package installed. But Puppet run fails. 

## Actual Behavior

Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install perl-doc' returned 1: Error: Nothing to do
Error: /Stage[main]/Perl/Package[perl-doc]/ensure: change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install perl-doc' returned 1: Error: Nothing to do

## Specifications

Facter output: 

aio_agent_build => 1.3.6
aio_agent_version => 1.3.6
augeas => {
  version => "1.4.0"
}
custom_auth_conf => false
disks => {
  sda => {
    model => "Virtual disk",
    size => "20.00 GiB",
    size_bytes => 21474836480,
    vendor => "VMware"
  },
  sr0 => {
    model => "VMware IDE CDR10",
    size => "4.03 GiB",
    size_bytes => 4329570304,
    vendor => "NECVMWar"
  }
}
dmi => {
  bios => {
    release_date => "09/21/2015",
    vendor => "Phoenix Technologies LTD",
    version => "6.00"
  },
  board => {
    manufacturer => "Intel Corporation",
    product => "440BX Desktop Reference Platform",
    serial_number => "None"
  },
  chassis => {
    asset_tag => "No Asset Tag",
    type => "Other"
  },
  manufacturer => "VMware, Inc.",
  product => {
    name => "VMware Virtual Platform",
    serial_number => "VMware-42 3c 1e 41 96 f3 72 11-9f 89 8a a6 eb 27 c0 a2",
    uuid => "423C1E41-96F3-7211-9F89-8AA6EB27C0A2"
  }
}
facterversion => 3.1.4
filesystems => xfs
identity => {
  gid => 0,
  group => "root",
  uid => 0,
  user => "root"
}
ip6tables_version => 1.4.21
iptables_version => 1.4.21
is_pe => false
is_virtual => true
kernel => Linux
kernelmajversion => 3.10
kernelrelease => 3.10.0-327.el7.x86_64
kernelversion => 3.10.0
last_run => Tue May 31 14:18:25:855088678 CEST 2016
load_averages => {
  15m => 0.05,
  1m => 0,
  5m => 0.01
}
memory => {
  swap => {
    available => "2.00 GiB",
    available_bytes => 2147381248,
    capacity => "0.00%",
    total => "2.00 GiB",
    total_bytes => 2147479552,
    used => "96.00 KiB",
    used_bytes => 98304
  },
  system => {
    available => "2.65 GiB",
    available_bytes => 2844315648,
    capacity => "28.46%",
    total => "3.70 GiB",
    total_bytes => 3975892992,
    used => "1.05 GiB",
    used_bytes => 1131577344
  }
}
mountpoints => {
  / => {
    available => "14.19 GiB",
    available_bytes => 15231549440,
    capacity => "18.75%",
    device => "/dev/mapper/centos-root",
    filesystem => "xfs",
    options => [
      "rw",
      "seclabel",
      "relatime",
      "attr2",
      "inode64",
      "noquota"
    ],
    size => "17.46 GiB",
    size_bytes => 18746441728,
    used => "3.27 GiB",
    used_bytes => 3514892288
  },
  /boot => {
    available => "372.55 MiB",
    available_bytes => 390647808,
    capacity => "24.99%",
    device => "/dev/sda1",
    filesystem => "xfs",
    options => [
      "rw",
      "seclabel",
      "relatime",
      "attr2",
      "inode64",
      "noquota"
    ],
    size => "496.67 MiB",
    size_bytes => 520794112,
    used => "124.12 MiB",
    used_bytes => 130146304
  }
}
os => {
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.2.1511",
    major => "7",
    minor => "2"
  },
  selinux => {
    config_mode => "permissive",
    config_policy => "targeted",
    current_mode => "permissive",
    enabled => true,
    enforced => false,
    policy_version => "28"
  }
}
package_provider => yum
partitions => {
  /dev/mapper/centos-root => {
    filesystem => "xfs",
    mount => "/",
    size => "17.47 GiB",
    size_bytes => 18756927488,
    uuid => "9afe1b51-41bc-4d23-9297-143b7448a56d"
  },
  /dev/mapper/centos-swap => {
    filesystem => "swap",
    size => "2.00 GiB",
    size_bytes => 2147483648,
    uuid => "1b2f5e5e-04a5-499a-bd1a-b1369193d845"
  },
  /dev/sda1 => {
    filesystem => "xfs",
    mount => "/boot",
    size => "500.00 MiB",
    size_bytes => 524288000,
    uuid => "861a0977-4040-48d0-8f4f-48ea01d3758f"
  },
  /dev/sda2 => {
    filesystem => "LVM2_member",
    size => "19.51 GiB",
    size_bytes => 20949499904,
    uuid => "Nxb7Of-hpjt-2a0n-uloe-vepc-cvHW-m1NNxo"
  }
}
path => /root/perl5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/root/bin:/sbin
pe_concat_basedir => /opt/puppetlabs/puppet/cache/pe_concat
pe_razor_server_version => package pe-razor-server is not installed
platform_symlink_writable => true
platform_tag => el-7-x86_64
processors => {
  count => 2,
  isa => "x86_64",
  models => [
    "Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz",
    "Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz"
  ],
  physicalcount => 1
}
puppet_files_dir_present => false
puppet_vardir => /opt/puppetlabs/puppet/cache
puppetversion => 4.3.2
r10k_environment => production
r10k_path => 
root_home => /root
ruby => {
  platform => "x86_64-linux",
  sitedir => "/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.1.0",
  version => "2.1.8"
}
selinux_custom_policy => targeted
service_provider => systemd
ssh_client_version_full => 6.6.1p1,
ssh_client_version_major => 6.6
ssh_client_version_release => 6.6.1
ssh_server_version_full => 6.6.1p1,
ssh_server_version_major => 6.6
ssh_server_version_release => 6.6.1
staging_http_get => curl
system_uptime => {
  days => 0,
  hours => 4,
  seconds => 15617,
  uptime => "4:20 hours"
}
timezone => CEST
virtual => vmware

I removed some information from facter output that contains sensitive information.

**Comment by alvagante** [comment]
Erm, did you solve the issue in some way? Why have you closed it?

**Comment by kariboe** [comment]
I made a mistake in my Puppet manifest. When included the right way it works. Thanks for your module!
