### ISSUE TITLE
Please update puppet forge with altest version

### ISSUE THREAD

**Issue by vthyng** [example42/puppet-perl#32]
## Expected Behavior 
Puppet forge to have latest commit available (perhaps a 'latest' tag?)

## Actual Behavior
version 2.0.24 is available from Aug 12, 2016, but does not include cpanm notest feature commit from Aug 24th, 2016.

## Steps to Reproduce the Problem

  1. go to https://forge.puppet.com/example42/perl
  2. see that latest version shown is Version 2.0.24 released Aug 12th 2016

**Comment by alvagante** [comment]
v2.0.25 tagged and published to the Forge.
