### ISSUE TITLE
Error while evaluating a Function Call, Cannot use empty string as a class name

### ISSUE THREAD

**Issue by kristiankorgaard** [example42/puppet-perl#35]
There is a problem with $perl::my_class defaults to an empty string '' - and puppet 5 does not like including empty class names.

The full error:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Cannot use empty string as a class name (file: /etc/puppetlabs/code/environments/qa/modules/perl/manifests/init.pp, line: 109, column: 5) on node host-56632-test

**Comment by alvagante** [comment]
Thanks for the PR, merged. note anyway that this module is not actively maintained anymore.
